openapi: 3.0.0

info:
  title: WateringCtl
  description: API contract for the communication with the wateringctl-firmware
  version: 0.0.1

paths:
  /schedule:
    get:
      tags:
      - "scheduler"
      summary: "Get the current schedule"
      responses:
        "200":
          description: "Fetch successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"

  /schedule/{day}:
    post:
      tags:
      - "scheduler"
      summary: "Append a new interval to to a specific day"
      parameters:
        - name: day
          in: path
          schema:
            $ref: "#/components/schemas/WeekDay"
          required: true
      requestBody:
        $ref: "#/components/requestBodies/IntervalRequest"
      responses:
        "400":
          description: "Malformed request"
        "409":
          description: "No more unoccupied slots available"

  /schedule/{day}/{index}:
    put:
      tags:
      - "scheduler"
      summary: "Alter a interval of a specific slot (by index) of a specific day"
      parameters:
        - name: day
          in: path
          schema:
            $ref: "#/components/schemas/WeekDay"
          required: true
        - name: index
          in: path
          schema:
            type: number
          required: true
      requestBody:
        $ref: "#/components/requestBodies/IntervalRequest"
      responses:
        "200":
          description: "Update successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    $ref: "#/components/schemas/Interval"
        "400":
          description: "Malformed request"


components:
  requestBodies:
    IntervalRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Interval'
  schemas:
    Interval:
      type: object
      properties:
        start:
          type: string
        end:
          type: string
        identifier:
          type: number
        index:
          type: number
          readOnly: true
        active:
          readOnly: true
          type: boolean
    ScheduledDay:
      type: array
      items:
        $ref: "#/components/schemas/Interval"
    WeekDay:
      type: string
      enum:
        - WEEKDAY_SU
        - WEEKDAY_MO
        - WEEKDAY_TU
        - WEEKDAY_WE
        - WEEKDAY_TH
        - WEEKDAY_FR
        - WEEKDAY_SA
    Scheduler:
      type: object
      properties:
        lastTickTime:
          readOnly: true
          type: string
        lastTickDay:
          readOnly: true
          type: string
    Schedule:
      type: object
      properties:
        days:
          type: object
          properties:
            WEEKDAY_SU:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_MO:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_TU:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_WE:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_TH:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_FR:
              $ref: "#/components/schemas/ScheduledDay"
            WEEKDAY_SA:
              $ref: "#/components/schemas/ScheduledDay"
        scheduler:
          $ref: "#/components/schemas/Scheduler"